Página de etapas
fga-eps-mds/2023-1-CAPJu-Front pull request #8
Opened 2023-05-06 13:52 UTC by victordsantoss

## Issue

Closes fga-eps-mds/2023-1-CAPJu-Doc#32
## Descrição

Foi criada um página de etapas juntamente com ações de criar, editar e excluir, seguindo o novo layout disponibilizado no [Figma](https://www.figma.com/file/Boim36mSfMhYFTPN7D4VVM/CAPJu?node-id=0-1&t=7i5HiJSx0rGY6MOK-0).

## Revisão 

- [ ] Tela de listagem de etapas
- [ ] Formulário de criação de etapa
- [ ] Ação de excluir etapa

## Pre-merge checklist 

- [ ] O Pull Request refere-se a um único assunto, um título claro e uma descrição em frases gramaticalmente corretas e completas.
- [ ] A ramificação está atualizada com a branch Develop.
- [ ] Os commits atendem o padrão especificado na política de contribuição.

## Screenshots (Se necessário)

| Antes | Depois |
| ----- | ------ |
| ![screencapture-capju-netlify-app-2023-05-06-10_49_53](https://user-images.githubusercontent.com/52058094/236628368-c99142c9-13ed-4c2b-b0ca-c428633a5ffb.png) | ![screencapture-localhost-3000-etapas-2023-05-06-10_48_52](https://user-images.githubusercontent.com/52058094/236628353-d9a748dc-c9b3-49ce-afed-1e29bca83d44.png)|

2023-05-06 14:25 UTC, senaarth requested changes

2023-05-06 14:25 UTC, senaarth commented on src/pages/Stages/index.tsx
> +
Cara, acho que aqui essa função poderia estar dentro de um modal de confirmação, no figma tem um, ele vai funcionar assim como o DenyModal da página de solicitações

2023-05-06 14:25 UTC, senaarth commented on src/services/stage/index.ts
Essa pasta aqui acho que vale mudar o nome pra stages, de resto o código tá perfeito, falo isso só pra seguir o padrão (por exemplo unidades ta units).

2023-05-08 20:08 UTC, victordsantoss commented on src/services/stage/index.ts
As correções foram realizadas.

2023-05-08 20:13 UTC, senaarth approved these changes
Agora simmm, to merjando!

2023-05-08 20:14 UTC, merged